"""Detection signals.

Signal 1 (this milestone): LLM classifier. Returns {"llm_score": 0.0-1.0, "reason": str},
where llm_score is the model's estimated probability the text is AI-generated.

Model is configurable so testing can use a cheap model while the demo uses the
full one. Defaults match planning.md:
  GROQ_MODEL           default llama-3.3-70b-versatile  (primary)
  GROQ_FALLBACK_MODEL  default openai/gpt-oss-120b      (retry on parse failure)
"""

import os
import json
import logging

from groq import Groq

log = logging.getLogger("provenance.signals")

PRIMARY_MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
FALLBACK_MODEL = os.getenv("GROQ_FALLBACK_MODEL", "openai/gpt-oss-120b")

SYSTEM_PROMPT = (
    "You are an expert detector of AI-generated text. Given a passage, estimate the "
    "probability that it was generated by an AI language model rather than written by a "
    "human. Judge it holistically: semantic and stylistic coherence, generic or formulaic "
    "phrasing, tonal uniformity, and hedging.\n"
    "Return ONLY a JSON object of the form "
    '{"llm_score": <number 0..1>, "reason": "<one sentence>"}. '
    "llm_score is the probability the text is AI-generated: 0.0 = certainly human, "
    "0.5 = genuinely uncertain, 1.0 = certainly AI."
)

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq()  # reads GROQ_API_KEY from the environment
    return _client


def _classify_once(text, model, client):
    """One LLM call. Returns (llm_score, reason). Raises on API/parse/validation error."""
    resp = client.chat.completions.create(
        model=model,
        temperature=0,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
    )
    data = json.loads(resp.choices[0].message.content)
    score = float(data["llm_score"])
    score = max(0.0, min(1.0, score))  # clamp into [0, 1]
    reason = str(data.get("reason", "")).strip()
    return score, reason


def signal_llm(text, client=None, model=None):
    """Run the LLM classifier with a fallback model and a safe default.

    On a parse/API failure, retry once with the fallback model. If that also fails,
    return a neutral score (0.5, uncertain) and log loudly. A confident wrong verdict
    is the costly error, so the failure mode is uncertainty, never a confident call.
    """
    client = client or _get_client()
    primary = model or PRIMARY_MODEL

    try:
        score, reason = _classify_once(text, primary, client)
        return {"llm_score": score, "reason": reason, "model": primary}
    except Exception as e:
        log.warning("LLM signal failed on %s (%s); retrying with %s",
                    primary, e, FALLBACK_MODEL)

    try:
        score, reason = _classify_once(text, FALLBACK_MODEL, client)
        return {"llm_score": score, "reason": reason, "model": FALLBACK_MODEL}
    except Exception as e:
        log.error("LLM signal fallback %s also failed (%s); defaulting to 0.5",
                  FALLBACK_MODEL, e)
        return {
            "llm_score": 0.5,
            "reason": "Classifier unavailable; defaulted to uncertain.",
            "model": None,
        }


if __name__ == "__main__":
    # Direct check (planning.md M3 verification): confirm a 0-1 score, not a label.
    from dotenv import load_dotenv
    load_dotenv()
    samples = {
        "ai_like": (
            "Artificial intelligence represents a transformative paradigm shift. It is "
            "important to note that stakeholders must collaborate to ensure responsible "
            "deployment across various sectors."
        ),
        "human_like": (
            "ok so i finally tried that ramen place downtown and honestly? underwhelming. "
            "way too much sodium, i was thirsty for like three hours after lol"
        ),
    }
    for name, txt in samples.items():
        print(name, "->", signal_llm(txt))
