"""Detection signals.

Signal 1 (this milestone): LLM classifier. Returns {"llm_score": 0.0-1.0, "reason": str},
where llm_score is the model's estimated probability the text is AI-generated.

Model is configurable so testing can use a cheap model while the demo uses the
full one. Defaults match planning.md:
  GROQ_MODEL           default llama-3.3-70b-versatile  (primary)
  GROQ_FALLBACK_MODEL  default openai/gpt-oss-120b      (retry on parse failure)
"""

import os
import re
import json
import logging
import statistics

from groq import Groq

log = logging.getLogger("provenance.signals")

PRIMARY_MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
FALLBACK_MODEL = os.getenv("GROQ_FALLBACK_MODEL", "openai/gpt-oss-120b")

SYSTEM_PROMPT = (
    "You are an expert detector of AI-generated text. Given a passage, estimate the "
    "probability that it was generated by an AI language model rather than written by a "
    "human. Judge it holistically: semantic and stylistic coherence, generic or formulaic "
    "phrasing, tonal uniformity, and hedging.\n"
    "Return ONLY a JSON object of the form "
    '{"llm_score": <number 0..1>, "reason": "<one sentence>"}. '
    "llm_score is the probability the text is AI-generated: 0.0 = certainly human, "
    "0.5 = genuinely uncertain, 1.0 = certainly AI."
)

_client = None


def _get_client():
    global _client
    if _client is None:
        _client = Groq()  # reads GROQ_API_KEY from the environment
    return _client


def _classify_once(text, model, client):
    """One LLM call. Returns (llm_score, reason). Raises on API/parse/validation error."""
    resp = client.chat.completions.create(
        model=model,
        temperature=0,
        response_format={"type": "json_object"},
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
    )
    data = json.loads(resp.choices[0].message.content)
    score = float(data["llm_score"])
    score = max(0.0, min(1.0, score))  # clamp into [0, 1]
    reason = str(data.get("reason", "")).strip()
    return score, reason


def signal_llm(text, client=None, model=None):
    """Run the LLM classifier with a fallback model and a safe default.

    On a parse/API failure, retry once with the fallback model. If that also fails,
    return a neutral score (0.5, uncertain) and log loudly. A confident wrong verdict
    is the costly error, so the failure mode is uncertainty, never a confident call.
    """
    client = client or _get_client()
    primary = model or PRIMARY_MODEL

    try:
        score, reason = _classify_once(text, primary, client)
        return {"llm_score": score, "reason": reason, "model": primary}
    except Exception as e:
        log.warning("LLM signal failed on %s (%s); retrying with %s",
                    primary, e, FALLBACK_MODEL)

    try:
        score, reason = _classify_once(text, FALLBACK_MODEL, client)
        return {"llm_score": score, "reason": reason, "model": FALLBACK_MODEL}
    except Exception as e:
        log.error("LLM signal fallback %s also failed (%s); defaulting to 0.5",
                  FALLBACK_MODEL, e)
        return {
            "llm_score": 0.5,
            "reason": "Classifier unavailable; defaulted to uncertain.",
            "model": None,
        }


def _words(text):
    return re.findall(r"[A-Za-z']+", text.lower())


def _sentences(text):
    return [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]


def _lean_low(value, ai_at, human_at):
    """Map a metric to a 0-1 AI-leaning sub-score where a LOW value means AI.

    value <= ai_at -> 1.0 (AI); value >= human_at -> 0.0 (human); linear between.
    """
    if human_at == ai_at:
        return 0.5
    return max(0.0, min(1.0, (human_at - value) / (human_at - ai_at)))


# Reference windows (provisional, tuned in M4). Each maps a metric to "how AI-like".
_STD_AI, _STD_HUMAN = 3.0, 9.0      # words-per-sentence stdev: uniform -> AI
_TTR_AI, _TTR_HUMAN = 0.55, 0.80    # type-token ratio: repetitive -> AI
_PUNC_AI, _PUNC_HUMAN = 0.05, 0.60  # expressive marks/sentence: flat -> AI

# Sub-signal weights inside stylometry (sum to 1). TTR is down-weighted because the
# type-token ratio barely discriminates on short submissions (it saturates high), so it
# stays a light tie-breaker for genuinely repetitive text rather than an equal vote.
_W_VAR, _W_TTR, _W_PUNC = 0.375, 0.25, 0.375

_MIN_WORDS = 25  # below this, stylometry is unreliable


def signal_stylometry(text):
    """Structural signal. Returns {"stylo_score": 0-1, "metrics": {...}}.

    stylo_score is the equal average of three AI-leaning sub-scores. Too-short text
    returns a neutral 0.5 so an unreliable structural read cannot swing the verdict.
    """
    words = _words(text)
    sentences = _sentences(text)
    n_words = len(words)

    if n_words < _MIN_WORDS or len(sentences) < 2:
        return {"stylo_score": 0.5,
                "metrics": {"note": "too short for reliable stylometry"}}

    # 1. Sentence-length uniformity: low stdev of words-per-sentence -> AI.
    lengths = [len(_words(s)) for s in sentences]
    std = statistics.pstdev(lengths)
    sub_var = _lean_low(std, _STD_AI, _STD_HUMAN)

    # 2. Lexical diversity: low type-token ratio -> AI.
    ttr = len(set(words)) / n_words
    sub_ttr = _lean_low(ttr, _TTR_AI, _TTR_HUMAN)

    # 3. Expressive punctuation: few !?;: and ellipses per sentence -> AI.
    expressive = len(re.findall(r"[!?;:]", text)) + len(re.findall(r"\.\.\.|…", text))
    punc_rate = expressive / len(sentences)
    sub_punc = _lean_low(punc_rate, _PUNC_AI, _PUNC_HUMAN)

    stylo_score = round(_W_VAR * sub_var + _W_TTR * sub_ttr + _W_PUNC * sub_punc, 4)
    return {
        "stylo_score": stylo_score,
        "metrics": {
            "sentence_len_std": round(std, 2), "sub_var": round(sub_var, 3),
            "type_token_ratio": round(ttr, 3), "sub_ttr": round(sub_ttr, 3),
            "expressive_per_sentence": round(punc_rate, 3), "sub_punc": round(sub_punc, 3),
        },
    }


if __name__ == "__main__":
    # Direct check (planning.md M3 verification): confirm a 0-1 score, not a label.
    from dotenv import load_dotenv
    load_dotenv()
    samples = {
        "ai_like": (
            "Artificial intelligence represents a transformative paradigm shift. It is "
            "important to note that stakeholders must collaborate to ensure responsible "
            "deployment across various sectors."
        ),
        "human_like": (
            "ok so i finally tried that ramen place downtown and honestly? underwhelming. "
            "way too much sodium, i was thirsty for like three hours after lol"
        ),
    }
    for name, txt in samples.items():
        print(name, "->", signal_llm(txt))
